### PR TITLE
Some tweaks and inclusions

### PR DESCRIPTION
**Pull request by feosuna1**
Not sure you're interested, but I adopted your code to meet one of my projects needs and it works (so far).

I made a few tweaks.  Some source code / whitespace clean up based on the style you used throughout the rest of the code, a few bug fixes, and some minor optimizations (e.g. returning early from a method).

Additionally, I added support for accurately identifying integers and floats (per YAML 1.1 specifications) and timestamps through a regular expression engine (RegExLite).

### CODE REVIEW

**Comment by patrickt** [comment]
Hi Enrique, 

I'm totally swamped right now, but I'll do my best to review these changes sometime soon. 
I'm not sure I want to incorporate another library like RegexKit into this; I was hoping YAMLKit could be a standalone library.

**Comment by feosuna1** [comment]
Yeah no issues, swamped is my middle name.

It's actually RegexKitLite (vice RegexKit).  RegexKitLite leverages Mac OS X's builtin ICU dynamic shared library.  Once you download RegexKitLite.[h & m] you can compile and the YAMLKit.framework becomes a standalone framework ready for inclusion into other projects.

**Comment by patrickt** [comment]
Okay, if it's just a pair of .h and .m files I have no problem including them. I just didn't want to pull in another .framework bundle. Thanks very much, Enrique.

**Comment by feosuna1** [comment]
Yup.  I originally started to go down that path but too many dependencies ensued. I updated the README to indicate instructions on how to get started. 
<code>yamlkit $ (cd extras && ./bootstrap && make)</code>

Will download the RegexLite h&m files and latest stable version of libyaml.

**Pull request closed without merging**
